### ISSUE TITLE
Michael Week 4 Review Ticket

### ISSUE THREAD

**Issue by Michaelc179** [Michaelc179/sleep#5]
# Score: x/10

### CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [ ] CB Create Task Coding requirements documented
- [ ] Runtime of Code(with comments) on Replit/Intellij

### Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [ ] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- [ ] Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
- [ ] Hack #1 Add Phone Number to Sign Up / Authorization screen
- [ ] Hack #2 Add logout to CRUD screen
- [ ] Hack #3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by Archkitten** [comment]
## Overall Score: 6/5
### Graded by Arch Huang

-----

### CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x] CB Create Task Coding requirements documented
- +1
- [x] Runtime of Code(with comments) on Replit/Intellij
- +1

Score: 2/2

-----

### Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [x] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- +1
- [x] Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
- +1
- [x] Hack 1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack 2 Add logout to CRUD screen
- [x] Hack 3 Add login_required to another portion of the project
- +1
- [x] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.
- +1

Score: 4/3
